### ISSUE TITLE
Bug in Excercise 5

### ISSUE THREAD

**Issue by VinayakaB** [techyourchance/unit-testing-in-android-course#7]
In Excercise 5, in EndpointResult class, getUsername() method returns UserId.

**Comment by VinayakaB** [comment]
https://github.com/techyourchance/unit-testing-in-android-course/blob/master/mockito_fundamentals/src/main/java/com/techyourchance/mockitofundamentals/exercise5/networking/UpdateUsernameHttpEndpointSync.java

**Comment by bhaskar253** [comment]
> In Excercise 5, in EndpointResult class, getUsername() method returns UserId.

@VinayakaB It is done intendedly, for testing our debugging skills. 
Instructor also mentioned in his corresponding lecture video that one bug is harder to find. I hope you can close this "Bug" as it is not actually a Bug but an exercise for course takers.

**Comment by techyourchance** [comment]
@bhaskar253, thanks for jumping in and clarifying this point. I missed this issue originally, so I really appreciate you taking the time to comment.
Closing.
